version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/.crt:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./ssl:/ssl/
#      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
  shiny:
    image: mdancho/shinyauth:latest
    container_name: shiny
    restart: unless-stopped
    expose:
      - 3838
#    volumes:
#      - /home/ubuntu/business_science_apps/:/srv/shiny-server/
#      - /home/ubuntu/log/shiny-server/:/var/log/shiny-server/
